### PR TITLE
Fix dtc syntax

### PR DESCRIPTION
**Pull request by brd**

### CODE REVIEW

**Comment by gonzoua** [comment]
The original syntax is actually correct. psci.dts is an overlay so it has to be compiled using dtc with overlay support. Warner is working in getting that into the tree

**Comment by brd** [comment]
Ah, do you have his patch then?

**Comment by gonzoua** [comment]
It was part of this review: https://reviews.freebsd.org/D3180
Patch itself is here: https://github.com/RobertCNelson/dtc/commit/dd6a0533e846e8d5e690a618fa35cc15a6103efb

**Comment by gonzoua** [comment]
You can download pre-compiled binaries here: https://people.freebsd.org/~gonzo/arm/rpi3-smp/

**Pull request closed without merging**
